//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLab.Tools.Db.SqlCe {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EasyLabRs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EasyLabRs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyLab.Tools.Db.SqlCe.EasyLabRs", typeof(EasyLabRs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a script file..
        /// </summary>
        internal static string CommandFileNotSet {
            get {
                return ResourceManager.GetString("CommandFileNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No .config file for parameter -file.
        /// </summary>
        internal static string ConfigDatabaseNoFile {
            get {
                return ResourceManager.GetString("ConfigDatabaseNoFile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The connection string is updated successfully..
        /// </summary>
        internal static string ConfigDatabaseOK {
            get {
                return ResourceManager.GetString("ConfigDatabaseOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Files (.config).
        /// </summary>
        internal static string ConfigFiles {
            get {
                return ResourceManager.GetString("ConfigFiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to update EasyLab connection string to {0}.
        ///Error: {1}.
        /// </summary>
        internal static string ConfigFileUpdateError {
            get {
                return ResourceManager.GetString("ConfigFileUpdateError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyLab Database Configuration.
        /// </summary>
        internal static string DatabaseConfiguration {
            get {
                return ResourceManager.GetString("DatabaseConfiguration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyLab Database Installation.
        /// </summary>
        internal static string DatabaseInstallation {
            get {
                return ResourceManager.GetString("DatabaseInstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please select a database file..
        /// </summary>
        internal static string DataBaseNotSet {
            get {
                return ResourceManager.GetString("DataBaseNotSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyLab Database Uninstallation.
        /// </summary>
        internal static string DatabaseUninstallation {
            get {
                return ResourceManager.GetString("DatabaseUninstallation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is NOT run as administrator..
        /// </summary>
        internal static string ElevatedError {
            get {
                return ResourceManager.GetString("ElevatedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The application is run as administrator..
        /// </summary>
        internal static string ElevatedOK {
            get {
                return ResourceManager.GetString("ElevatedOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is installed successfully..
        /// </summary>
        internal static string InstallDatabaseOK {
            get {
                return ResourceManager.GetString("InstallDatabaseOK", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scripts (.sql).
        /// </summary>
        internal static string SqlScripts {
            get {
                return ResourceManager.GetString("SqlScripts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to The database is uninstalled successfully..
        /// </summary>
        internal static string UninstallDatabaseOK {
            get {
                return ResourceManager.GetString("UninstallDatabaseOK", resourceCulture);
            }
        }
    }
}
