//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EasyLab.WS.DeviceAgent {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class EasyLabRs {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EasyLabRs() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("EasyLab.WS.DeviceAgent.EasyLabRs", typeof(EasyLabRs).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CleanProcessedRecords.cleanupSvc.Cleanup({0}) end at:{1}.
        /// </summary>
        public static string CLEAN_UP_END {
            get {
                return ResourceManager.GetString("CLEAN_UP_END", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to cleanProcessedRecordsTimer: GetCleanProcessedRecordTimerInterval() failed with exception : {0}.
        /// </summary>
        public static string CLEAN_UP_FAILED_GET_TIME_INTERVAL {
            get {
                return ResourceManager.GetString("CLEAN_UP_FAILED_GET_TIME_INTERVAL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing CleanUpProcessedRecords: {0}.
        /// </summary>
        public static string CLEAN_UP_FAILED_WITH_EXCEPTION {
            get {
                return ResourceManager.GetString("CLEAN_UP_FAILED_WITH_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CleanProcessedRecords.cleanupSvc.Cleanup({0}) start at:{1}.
        /// </summary>
        public static string CLEAN_UP_START {
            get {
                return ResourceManager.GetString("CLEAN_UP_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not get device port setting，please check your settings..
        /// </summary>
        public static string DEVICE_PORT_NOT_SET {
            get {
                return ResourceManager.GetString("DEVICE_PORT_NOT_SET", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Error on starting service: {0}.
        /// </summary>
        public static string FAILED_START_DEVICE_SERVICE_WITH_EXCEPTION {
            get {
                return ResourceManager.GetString("FAILED_START_DEVICE_SERVICE_WITH_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to .
        /// </summary>
        public static string INVALID_RESOURCE_ID {
            get {
                return ResourceManager.GetString("INVALID_RESOURCE_ID", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stopping Device Agent service..
        /// </summary>
        public static string LOG_BEGIN_STOP_DEVICE_SERVICE {
            get {
                return ResourceManager.GetString("LOG_BEGIN_STOP_DEVICE_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting Device Agent service..
        /// </summary>
        public static string LOG_DEVICE_SERVICE_START {
            get {
                return ResourceManager.GetString("LOG_DEVICE_SERVICE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Agent service started..
        /// </summary>
        public static string LOG_DEVICE_SERVICE_STARTED {
            get {
                return ResourceManager.GetString("LOG_DEVICE_SERVICE_STARTED", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Device Agent service stopped..
        /// </summary>
        public static string LOG_END_STOP_DEVICE_SERVICE {
            get {
                return ResourceManager.GetString("LOG_END_STOP_DEVICE_SERVICE", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to LdapSyncSettings.Synchronize begin at: {0}.
        /// </summary>
        public static string LOG_LDAP_SYNC_SETTINGS_BEGIN_SYNC {
            get {
                return ResourceManager.GetString("LOG_LDAP_SYNC_SETTINGS_BEGIN_SYNC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Processing Messages: {0}.
        /// </summary>
        public static string LOG_MESSAGE_FAILED_PROCESS_WITH_EXCEPTION {
            get {
                return ResourceManager.GetString("LOG_MESSAGE_FAILED_PROCESS_WITH_EXCEPTION", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Timer &lt;{0}&gt; is processing messages..
        /// </summary>
        public static string LOG_MESSAGE_TYPE_IS_PROCESS {
            get {
                return ResourceManager.GetString("LOG_MESSAGE_TYPE_IS_PROCESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Starting rest service....
        /// </summary>
        public static string LOG_REST_SERVICE_START {
            get {
                return ResourceManager.GetString("LOG_REST_SERVICE_START", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rest service Started, base address is: {0}.
        /// </summary>
        public static string LOG_REST_SERVICE_STARTED_WITH_BASE_ADDRESS {
            get {
                return ResourceManager.GetString("LOG_REST_SERVICE_STARTED_WITH_BASE_ADDRESS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyLab is the best software of lab manage, DeviceAgent support some service for client. All RightCopy is Campnano.
        /// </summary>
        public static string ServiceDescription {
            get {
                return ResourceManager.GetString("ServiceDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to EasyLab DeviceAgent  Service.
        /// </summary>
        public static string ServiceDisplayName {
            get {
                return ResourceManager.GetString("ServiceDisplayName", resourceCulture);
            }
        }
    }
}
